ALTER TABLE Gps
	ADD CONSTRAINT FOREIGN KEY (DriverID) REFERENCES Drivers (DriverID) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD CONSTRAINT FOREIGN KEY (TruckID) REFERENCES Trucks (TruckID) ON DELETE CASCADE ON UPDATE CASCADE;

	
	